version: '3'
services:
  php:
    container_name: ld-php
    build:
      context: ./
      dockerfile: /docker/php/mysql.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    tty: true
    networks:
      - ld-net
  nginx:
    container_name: ld-nginx
    image: nginx:1.12.2
    working_dir: /var/www
    volumes:
       - php
       - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - ld-net
  composer:
    container_name: ld-composer
    command: ["composer", "update"]
    image: composer:latest
    tty: true
    working_dir: /var/www
    volumes:
      - php
    depends_on:
      - php
    networks:
      - ld-net
networks:
  ld-net:
volumes:
  ld-data:
