version: '3'
services:
  php:
    container_name: ld-php
    build:
      context: ./
      dockerfile: /docker/php/main.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    tty: true
  nginx:
    container_name: ld-nginx
    image: nginx:latest
    working_dir: /var/www
    volumes:
       - php
       - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  redis:
    container_name: ld-redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    image: redis   
    volumes:
      - .docker/redis/redis.conf:/usr/local/etc/redis/redis.conf 
      - ld-data:/var/redis/data 
  composer:
    container_name: ld-composer
    command: ["composer", "update"]
    image: composer:latest
    tty: true
    working_dir: /var/www
    volumes:
      - php
    depends_on:
      - php
  supervisor:
    container_name: ld-supervisor
    image:  kdelfour/supervisor-docker
    volumes:
       - ./docker/supervisor:/etc/supervisor/conf.d
       - ld-data:/var/supervisor/data 
volumes:
  ld-data: