#!/bin/bash

# Run with Mysql
#docker-compose -f docker-compose.yml -f docker/docker-compose.mysql.yml down

# Run with Mysql/phpadmin
docker-compose -f docker-compose.yml \
               -f docker/docker-compose.mysql.yml \
               -f docker/docker-compose.phpmyadmin.yml \
                down