version: '3'
services:
  mysql:
    container_name: ld-mysql
    image: mysql:latest
    volumes:
      - ld-data:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=mysql"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - "3306:3306" 
