version: '3'
services:
  php:
    container_name: ld-php
    build:
      context: ./
      dockerfile: /docker/php/postgres.dockerfile
    working_dir: /var/www
    environment:
      - "DB_PORT=5432"
      - "DB_HOST=postgres"
      - "DB_CONNECTION=pgsql"
      - "DB_DATABASE=ld-database"
      - "DB_USER=root"
      - "DB_PASSWORD=root"