version: '3'
services:
  redis:
    container_name: ld-redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    image: redis   
    volumes:
      - .docker/redis/redis.conf:/usr/local/etc/redis/redis.conf 
      - ld-data:/var/redis/data 
    networks:
      - ld-net
    environment:
      - "REDIS_HOST=redis"
      - "REDIS_PASSWORD=null"
      - "REDIS_PORT=6379"