version: '3'
services:
  adminer:
    container_name: ld-adminer
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - ld-net
    depends_on:
      - postgres
    links:
      - postgres